### ISSUE TITLE
An error about python demo_model_visual.py

### ISSUE THREAD

**Issue by emilyemliyM** [kamanphoebe/MotionDetection#3]
![image](https://user-images.githubusercontent.com/88700988/182294335-6ed322d2-95ce-4393-aadc-99ac5532c3f7.png)
![image](https://user-images.githubusercontent.com/88700988/182294390-cd67b544-6f6a-4120-baa5-1013dba80c2d.png)

There is no "demo_raw" dir in the repo.

Really thanks.

**Comment by kamanphoebe** [comment]
Thanks for reporting the mistake! I've already fixed the bug. Either fetching the latest version or simply changing the path to "./demo_raw_flow" should work now.

Please let me know if you have any further problems :)
