### ISSUE TITLE
Dear author, where is the "flowgraph_fastflow.py"  or ''flowgraph_raft.py"?

### ISSUE THREAD

**Issue by emilyemliyM** [kamanphoebe/MotionDetection#4]
![image](https://user-images.githubusercontent.com/88700988/182378003-03a51dea-10e9-4158-a038-6b51cba70a11.png)

BTW, the script with "expand"  means that it contains the key frame and non-keyframes?

Thanks a lot.

**Comment by kamanphoebe** [comment]
The scripts `flowgraph_fastflow.py` and `flowgraph_raft.py` should actually be `flow_fastflow.py` and `flow_raft.py` under the `dev` directory. Sorry for the typos and I've corrected the README.md.

The word "expand" means that both non-keyframes and nearby objects are added to the dataset. You can find more information in Step 7 of [Implement the complete pipeline](https://github.com/kamanphoebe/MotionDetection#implement-the-complete-pipeline).
