### ISSUE TITLE
dear author, dir name  (raftkitti_kitti  or  raft_kitti)

### ISSUE THREAD

**Issue by emilyemliyM** [kamanphoebe/MotionDetection#6]
![image](https://user-images.githubusercontent.com/88700988/182409451-de21e9bf-5af5-43c7-8ac5-e8ac51d6eee7.png)

Is that both to be the "raft_kitti".

By the way ,the raft weights can not be load.

Really thanks.

**Comment by kamanphoebe** [comment]
Yes, they should be "raft_kitti". Thanks for giving me a hand for eliminating the annoying typos :(

Could you provide the error message of failing to load the raft weights?

**Comment by kamanphoebe** [comment]
Closing the issue due to inactive status. Feel free to re-open if necessary :)
