### ISSUE TITLE
Dear author, generate_labels error ,thanks

### ISSUE THREAD

**Issue by emilyemliyM** [kamanphoebe/MotionDetection#7]
![image](https://user-images.githubusercontent.com/88700988/184529854-9ee4bac0-9cb4-44d8-b4a3-14b644d208c5.png)

return none

**Comment by kamanphoebe** [comment]
This error appears because the `re.search()` command found nothing. Could you check whether the optical data under the `dev/fastflow_kitti/flow_train` directory are named in the format `seq_([0-9]*)_img_([0-9]*)_(.*).npy`? (e.g. `seq_12_img_002_83459651359.npy`)

**Comment by kamanphoebe** [comment]
Closing the issue due to inactive status. Feel free to re-open if necessary :)
